platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/bosh-ecosystem-concourse

inputs:
- name: input_repo
- name: python-release

outputs:
- name: output_repo

run:
  path: python-release/ci/tasks/shared/bump-python-package.sh

params:
  GIT_USER_NAME: CI Bot
  GIT_USER_EMAIL: bots@cloudfoundry.org
  PACKAGES:
  PRIVATE_YML:
  RELEASE_DIR:
