---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/golang-release-security-scanner

inputs:
- name: patched_cves
- name: golang-release

run:
  path: golang-release/ci/tasks/shared/ensure-cve-checker-succeeded.sh

params:
