---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/cli

inputs:
- name: python-3.10
- name: python-3.11
- name: python-3.12
- name: python-release
- name: stemcell

outputs:
- name: python-release
  path: bumped-python-release

run:
  path: python-release/ci/tasks/bump.sh

params:
  PRIVATE_YAML: ~
