---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/cli

inputs:
- name: python-release
- name: semver

outputs:
- name: version-tag
- name: bumped-semver
- name: finalized-release

params:
  PRIVATE_YML: replace-me

run:
  path: python-release/ci/tasks/finalize.sh
