---
name: test

releases:
- name: python
  version: create
  url: file://.

stemcells:
- alias: default
  os: ((os))
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: python-3.10-test
  azs: [z1]
  instances: 1
  jobs:
  - name: python-3.10-((job-name))
    release: python
    properties: {}
  vm_type: default
  vm_extensions: ((ephemeral-disk))
  stemcell: default
  networks:
  - name: default
- name: python-3.11-test
  azs: [z1]
  instances: 1
  jobs:
  - name: python-3.11-((job-name))
    release: python
    properties: {}
  vm_type: default
  vm_extensions: ((ephemeral-disk))
  stemcell: default
  networks:
  - name: default
- name: python-3.12-test
  azs: [z1]
  instances: 1
  jobs:
  - name: python-3.12-((job-name))
    release: python
    properties: {}
  vm_type: default
  vm_extensions: ((ephemeral-disk))
  stemcell: default
  networks:
  - name: default